# Eureka Server 설정
server:
  port: 8761  # Eureka Server 표준 포트 (8761)

spring:
  application:
    name: eureka-server  # 서비스 이름 (다른 서비스들이 이 이름으로 인식)

eureka:
  client:
    # MSA 핵심: Eureka Server 자체는 다른 Eureka Server에 등록하지 않음
    register-with-eureka: false  # 자기 자신을 등록하지 않음
    fetch-registry: false        # 다른 서비스 정보를 가져오지 않음
  server:
    # 개발 환경에서만 사용: 서비스가 일시적으로 다운되어도 레지스트리에서 제거
    enable-self-preservation: false