# API Gateway 설정
server:
  port: 8080  # 클라이언트가 접근하는 단일 진입점 포트

spring:
  application:
    name: api-gateway  # API Gateway 서비스 이름
  cloud:
    gateway:
      discovery:
        locator:
          # MSA 핵심: 서비스 디스커버리 활성화
          enabled: true              # Eureka에서 서비스 자동 발견
          lower-case-service-id: true # 서비스 이름을 소문자로 변환
      
      # MSA 핵심: 라우팅 규칙 정의
      routes:
        # 회원 서비스 라우팅
        - id: member-service
          uri: lb://member-service    # lb:// = 로드밸런싱, member-service는 Eureka에 등록된 서비스명
          predicates:
            - Path=/api/members/**    # /api/members/로 시작하는 모든 요청
          filters:
            - StripPrefix=1           # /api 접두사 제거 (/api/members/1 → /members/1)
        
        # 게시판 서비스 라우팅
        - id: board-service
          uri: lb://board-service     # board-service로 로드밸런싱
          predicates:
            - Path=/api/boards/**     # /api/boards/로 시작하는 모든 요청
          filters:
            - StripPrefix=1           # /api 접두사 제거

# MSA 핵심: 서비스 레지스트리 연결
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server 주소

# 개발/디버깅용 로깅 설정
logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Gateway 동작 로깅
    org.springframework.web: DEBUG             # 웹 요청 로깅